name: Node CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install global dependencies
        run: npm install --global pnpm
      - name: Build and test
        run: |
          pnpm install
          pnpm -r run build
          pnpm -r run test
        env:
          CI: true
